DOMAIN = "rte_ecowatt"
CONF_CLIENT_ID = "api_client_id"
CONF_CLIENT_SECRET = "api_client_secret"
CONF_ENEDIS_LOAD_SHEDDING = "enedis_load_shedding"
CONF_SENSORS = "sensors"
CONF_SENSOR_UNIT = "unit"
CONF_SENSOR_SHIFT = "shift"

BASE_URL = "https://digital.iservices.rte-france.com"
TOKEN_URL = f"{BASE_URL}/token/oauth/"

ATTR_LEVEL_CODE = "level_code"
ATTR_GENERATION_TIME = "generation_time"
ATTR_PERIOD_START = "period_start"
ATTR_PERIOD_END = "period_end"
